services:
  ktranslate_flow:
    image: kentik/ktranslate:latest
    restart: always
    pull_policy: always
    environment:
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - OTEL_EXPORTER_OTLP_COMPRESSION=${OTEL_SERVICE_NAME}
    depends_on:
      - alloy
    command:
      - --format=otel
      - --otel.protocol=grpc
      - --otel.endpoint=http://alloy:4317/
      - --nf.source=${NF_SOURCE}
      - --metalisten=0.0.0.0:9996
      - --dns=127.0.0.1:53
      - --sinks=otel
      - --metrics=jchf
      - --tee_logs=true
      - --service_name=flow
      - --max_flows_per_message=100
      - --rollups=s_sum,bytes_by_flow,in_bytes+out_bytes,src_addr,dst_addr,l4_src_port,l4_dst_port,protocol,custom_str.application,device_name,custom_str.src_host,custom_str.dst_host,src_geo,dst_geo
#      - --rollups=s_sum,pkts_by_flow,in_pkts+out_pkts,src_addr,dst_addr,l4_src_port,l4_dst_port,protocol,custom_str.application,device_name,custom_str.src_host,custom_str.dst_host,src_geo,dst_geo
      - --rollup_keep_undefined=true
    ports:
      - 9995:9995/udp
      - 9996:9996
  ktranslate_snmp:
    image: kentik/ktranslate:latest
    restart: always
    pull_policy: always
    environment:
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - OTEL_EXPORTER_OTLP_COMPRESSION=${OTEL_SERVICE_NAME}
    volumes:
      - type: bind
        source: ./snmp.yaml
        target: /snmp.yaml
    depends_on:
      - alloy
    command:
      - --format=otel
      - --otel.protocol=grpc
      - --otel.endpoint=http://alloy:4317/
      - --snmp=/snmp.yaml
      - --metalisten=0.0.0.0:9997
      - --dns=127.0.0.1:53
      - --sinks=otel
      - --metrics=jchf
      - --tee_logs=true
      - --service_name=snmp
      - --max_flows_per_message=100
      - --snmp_discovery_on_start=true
      - --snmp_discovery_min=720
    ports:
      - 9997:9997
      - 1620:1620/udp
  alloy:
    image: grafana/alloy:latest
    restart: always
    pull_policy: always
    environment:
      - GC_OTLP_URL=${GC_OTLP_URL}
      - GC_OTLP_ACCOUNT=${GC_OTLP_ACCOUNT}
      - GC_OTLP_KEY=${GC_OTLP_KEY}
    volumes:
      - type: bind
        source: ./config.alloy
        target: /config.alloy
    ports:
      - 4317:4317
      - 12346:12346
    command:
      - --server.http.listen-addr=0.0.0.0:12346
      - --storage.path=/var/lib/alloy/data
      - --stability.level=experimental
      - run
      - /config.alloy
  host-sflow:
    image: sflow/host-sflow
    container_name: host-sflow
    restart: unless-stopped
    environment:
      - COLLECTOR=127.0.0.1
      - PORT=9995
      - NET=ens4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
