{
 "title": "SNMP overview",
 "tags": [ "snmp" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "${VAR_PROMETHEUS_DATASOURCE}" },
   { "name": "job", "label": "Job", "query": "${VAR_JOB}" },
   {
    "name": "instance",
    "label": "Device",
    "query": {
     "query": "label_values(kentik_snmp_Uptime{job=~\"$job\"},device_name)"
    }
   },
   {
    "name": "ifName",
    "label": "Interface name",
    "query": {
     "query": "label_values(kentik_snmp_if_OperStatus{device_name=\"$instance\", job=\"$job\"},if_interface_name)"
    }
   },
   { "name": "adhoc", "label": "Ad hoc filters" },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device name",
   "type": "stat",
   "description": "System name.\n",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,device_name, SysName) (\n  kentik_snmp_Uptime{device_name=~\"$instance\"}\n)",
     "legendFormat": "{{device_name}}: Device name"
    }
   ]
  },
  {
   "title": "System Description",
   "type": "stat",
   "description": "\n",
   "gridPos": { "h": 2, "w": 21, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,SysDescr) (\n  kentik_snmp_Uptime{device_name=~\"$instance\"}\n)",
     "legendFormat": "{{sysDescr}}: Description"
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,SysLocation, SysContact, instrumentation_name, src_addr) (\r\n  kentik_snmp_Uptime{device_name=~\"$instance\"}\r\n)",
     "legendFormat": "{{SysLocation}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage.",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,device_name) (\n  kentik_snmp_CPU{device_name=~\"$instance\"}\n)",
     "legendFormat": "{{device_name}}: CPU utilization"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "Memory utilization.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,device_name) (\n  kentik_snmp_MemoryUtilization{device_name=~\"$instance\"}\n)",
     "legendFormat": "{{device_name}}: Memory utilization"
    }
   ]
  },
  {
   "title": "SysName",
   "type": "stat",
   "description": "System name.\n",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,device_name, SysName) (\n  kentik_snmp_Uptime{device_name=~\"$instance\"}\n)",
     "legendFormat": "{{device_name}}: Device name"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The time since the network management portion of the system was last re-initialized.\n",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kentik_snmp_Uptime{device_name=~\"$instance\"}/100",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  { "title": "Network interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Interfaces",
   "type": "table",
   "description": "Network interfaces overview.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (job,device_name,if_interface_name,if_Alias,if_Description,if_OperStatus,if_AdminStatus,if_Speed,if_Type) (\n  kentik_snmp_if_OperStatus{job=~\"$job\",device_name=~\"$instance\",if_interface_name=~\"$ifName\",if_AdminStatus!=\"\"}\n)",
     "legendFormat": "{{if_Description}}: status"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "Network interface traffic out.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name,if_interface_name,if_Description) (\n  rate(kentik_snmp_ifHCOutOctets{job=~\"$job\",device_name=~\"$instance\",if_interface_name=~\"$ifName\"} [$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9\n)",
     "legendFormat": "{{if_interface_name}}: transmitted"
    },
    {
     "expr": "topk(25,\n  \n  (\n  sum by (job,device_name,if_interface_name,if_Description) (\n  rate(kentik_snmp_ifHCInOctets{job=~\"$job\",device_name=~\"$instance\",if_interface_name=~\"$ifName\"}[$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9\n)",
     "legendFormat": "{{if_interface_name}}: received"
    }
   ]
  },
  {
   "title": "Traffic Percentages",
   "type": "timeseries",
   "description": "As calculated during polling by ktranslate. Only available on interfaces that report their ifSpeed.  Maybe differ from byte calculations show due to built in behaviors of Prometheus rates.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(25,\r\n  (\r\n  sum by (job,device_name,if_interface_name,if_Description) (\r\n  rate(kentik_snmp_IfOutUtilization{job=~\"$job\",device_name=~\"$instance\",if_interface_name=~\"$ifName\"} [$__rate_interval])\r\n)\r\n)\r\n)",
     "legendFormat": "{{if_Description}}: transmitted"
    },
    {
     "expr": "topk(25,\r\n  (\r\n  sum by (job,device_name,if_interface_name,if_Description) (\r\n  rate(kentik_snmp_IfInUtilization{job=~\"$job\",device_name=~\"$instance\",if_interface_name=~\"$ifName\"} [$__rate_interval])\r\n)\r\n)\r\n)",
     "legendFormat": "{{if_Description}}: received"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "description": "Network interface errors in.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  kentik_snmp_ifInErrors{device_name=~\"$instance\"}\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: errors in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  kentik_snmp_ifOutErrors{device_name=~\"$instance\"}\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: errors out"
    }
   ]
  },
  {
   "title": "Dropped packets",
   "type": "timeseries",
   "description": "Network interface discards in.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  irate(kentik_snmp_ifInDiscards{device_name=~\"$instance\",if_interface_name=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: dropped in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  irate(kentik_snmp_ifOutDiscards{device_name=~\"$instance\",if_interface_name=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: dropped out"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  irate(ifInUnknownProtos{device_name=~\"$instance\",if_interface_name=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: unknown dropped in"
    }
   ]
  },
  {
   "title": "Unicast",
   "type": "timeseries",
   "description": "Network interface unicast packets in.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  kentik_snmp_ifHCInUcastPkts{device_name=~\"$instance\",if_interface_name=~\"$ifName\"}\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: unicast in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  kentik_snmp_ifHCOutUcastPkts{device_name=~\"$instance\",if_interface_name=~\"$ifName\"}\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: unicast out"
    }
   ]
  },
  {
   "title": "Broadcast",
   "type": "timeseries",
   "description": "Network interface broadcast packets in.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  kentik_snmp_ifHCInBroadcastPkts{device_name=~\"$instance\",if_interface_name=~\"$ifName\"}\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: broadcast in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  kentik_snmp_ifHCOutBroadcastPkts{device_name=~\"$instance\",if_interface_name=~\"$ifName\"}\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: broadcast out"
    }
   ]
  },
  {
   "title": "Multicast",
   "type": "timeseries",
   "description": "Network interface multicast packets in.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  irate(kentik_snmp_ifHCInMulticastPkts{device_name=~\"$instance\",if_interface_name=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: multicast in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (device_name,if_interface_name) (\n  irate(kentik_snmp_ifHCOutMulticastPkts{device_name=~\"$instance\",if_interface_name=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{if_interface_name}}: multicast out"
    }
   ]
  },
  {
   "title": "FRU (Components)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "FRU status",
     "type": "table",
     "description": "Field replaceable unit status",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "(\n  sum by (job,instance,entPhysicalName,cefcFRUPowerOperStatus) (\n  cefcFRUPowerOperStatus{job=~\"$job\",instance=~\"$instance\"}\n)\n)!=0",
       "legendFormat": "{{entPhysicalName}}: FRU status"
      }
     ]
    }
   ]
  },
  {
   "title": "Fibre channel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "FC buffer-to-buffer credit",
     "type": "timeseries",
     "description": "The current value of receive buffer-to-buffer credits for this port.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  fcIfCurrRxBbCredit{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)\n)",
       "legendFormat": "{{ifDescr}}: credit receive"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  fcIfCurrTxBbCredit{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)\n)",
       "legendFormat": "{{ifDescr}}: credit transmit"
      }
     ]
    },
    {
     "title": "Network FC errors",
     "type": "timeseries",
     "description": "-TxWaitCount: The number of times the FC-port waited due to lack of transmit credits.\n\n-FramesDiscard: The number of frames discarded by the FC-port.\n\n-TxWtAvgBBCreditTransitionToZero: increments if the credit available is zero for 100 ms.\n\n-BBCreditTransistionFromZero: increments if the transmit b2b credit is zero.\n\n-BBCreditTransistionToZero: increments if the receive b2b credit is zero.\n\n-InvalidTxWords: The number of invalid transmission words detected by the FC-Port.\n\n-InvalidCrcs: The number of invalid CRCs detected by the FC-Port.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfTxWaitCount{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifDescr}}: fcIfTxWaitCount"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfFramesDiscard{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifDescr}}: fcIfFramesDiscard"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfTxWtAvgBBCreditTransitionToZero{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifDescr}}: fcIfTxWtAvgBBCreditTransitionToZero"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcHCIfBBCreditTransistionFromZero{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifDescr}}: fcHCIfBBCreditTransistionFromZero"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcHCIfBBCreditTransistionToZero{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifDescr}}: fcHCIfBBCreditTransistionToZero"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfInvalidCrcs{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifDescr}}: fcIfInvalidCrcs"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfInvalidTxWords{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifDescr}}: fcIfInvalidTxWords"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "description": "Temperature sensor.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "(\n  avg by (device_name,entity_description) (\nkentik_snmp_sensor_value{device_name=\"$instance\",sensor_type=\"celsius\"}\n)/10\n)!=0",
       "legendFormat": "{{entity_description}}"
      }
     ]
    },
    {
     "title": "DC voltage",
     "type": "timeseries",
     "description": "DC voltage sensor.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "(\n  avg by (device_name,entity_description) (\nkentik_snmp_sensor_value{device_name=\"$instance\",sensor_type=\"voltsDC\"}\n)/10\n)!=0",
       "legendFormat": "{{entity_description}}"
      }
     ]
    },
    {
     "title": "Power",
     "type": "timeseries",
     "description": "Power used in Watts.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "(\n  avg by (device_name,entity_description) (\nkentik_snmp_sensor_value{device_name=\"$instance\",sensor_type=\"watts\"}\n)/10\n)!=0",
       "legendFormat": "{{entity_description}}"
      }
     ]
    },
    {
     "title": "Receive/Transmit power",
     "type": "timeseries",
     "description": "Receive/Transmit power.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "targets": [
      {
       "expr": "(\n  avg by (device_name,entity_description) (\nkentik_snmp_sensor_value{device_name=\"$instance\",sensor_type=\"dBm\"}\n)\n)!=0",
       "legendFormat": "{{entity_description}}"
      }
     ]
    },
    {
     "title": "Fan speed",
     "type": "timeseries",
     "description": "Fan speed.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "(\n  avg by (device_name,entity_description) (\nkentik_snmp_sensor_value{device_name=\"$instance\",sensor_type=\"rpm\"}\n)/10\n)!=0",
       "legendFormat": "{{entity_description}}"
      }
     ]
    }
   ]
  }
 ]
}