{
 "title": "Ktranslate Flow Summary",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "device_name",
    "query": {
     "query": "label_values(network_io_by_flow{device_name=~\".*\"},device_name)"
    }
   },
   {
    "name": "network_local_address",
    "label": "network_local_address",
    "query": {
     "query": "label_values(network_io_by_flow{device_name=~\"$device_name\"},network_local_address)"
    }
   },
   {
    "name": "network_peer_address",
    "label": "network_peer_address",
    "query": {
     "query": "label_values(network_io_by_flow{device_name=~\"$device_name\"},network_peer_address)"
    }
   },
   {
    "name": "network_protocol_name",
    "label": "network_protocol_name",
    "query": {
     "query": "label_values(network_io_by_flow{device_name=~\"$device_name\"},network_protocol_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Devices Sending Flow",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(device_name) (network_io_by_flow{device_name=~\"$device_name\",network_local_address=~\"$network_local_address\",network_peer_address=~\"$network_peer_address\",network_protocol_name=~\"$network_protocol_name\"})",
     "legendFormat": "Source: {{network_local_address}} - Dest: {{network_peer_address}}"
    }
   ]
  },
  {
   "title": "Total Traffic by Device",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Total Traffic over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Top Sources",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(network_io_by_flow{device_name=~\"$device_name\",network_local_address=~\"$network_local_address\",network_peer_address=~\"$network_peer_address\",network_protocol_name=~\"$network_protocol_name\"})",
     "legendFormat": "{{network_local_address}}"
    }
   ]
  },
  {
   "title": "Top Destinations",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "panelId": 10 }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Application Total Bytes",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 19 },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Total Traffic by Application",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Application Traffic over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(network_protocol_name) (network_io_by_flow{device_name=~\"$device_name\",network_local_address=~\"$network_local_address\",network_peer_address=~\"$network_peer_address\",network_protocol_name=~\"$network_protocol_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Conversations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Conversation Total Bytes",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Total Traffic by Conversation",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Conversation Traffic over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(device_name,network_local_address,network_peer_address) (network_io_by_flow{device_name=~\"$device_name\",network_local_address=~\"$network_local_address\",network_peer_address=~\"$network_peer_address\",network_protocol_name=~\"$network_protocol_name\"})",
     "legendFormat": "{{network_local_address}} {{network_peer_address}}"
    }
   ]
  },
  { "title": "Sankey Diagram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Conversations",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  { "title": "Geo Maps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Top Flow Sources",
   "type": "geomap",
   "description": "Private IP's will not show on map. Country information is based on MaxMind GeoIP database",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by(network_local_country) (network_io_by_flow{device_name=~\"$device_name\",network_local_address=~\"$network_local_address\",network_peer_address=~\"$network_peer_address\",network_protocol_name=~\"$network_protocol_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Flow Destinations",
   "type": "geomap",
   "description": "Private IP's will not show on map. Country information is based on MaxMind GeoIP database",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum by(network_peer_country) (network_io_by_flow{device_name=~\"$device_name\",network_local_address=~\"$network_local_address\",network_peer_address=~\"$network_peer_address\",network_protocol_name=~\"$network_protocol_name\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}