{
 "title": "Fleet overview",
 "tags": [ "Network Monitoring" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "${VAR_PROMETHEUS_DATASOURCE}" },
   { "name": "job", "label": "Job", "query": "${VAR_JOB}" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kentik_snmp_Uptime{job=~\"$job\"},device_name)"
    }
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Network devices",
   "type": "table",
   "description": "Network devices overview.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (device_name) (\n  kentik_snmp_if_OperStatus{job=~\"$job\",device_name=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Interfaces"
    },
    {
     "expr": "sum by (job,device_name,SysName) (\n  kentik_snmp_Uptime{job=~\"$job\",device_name=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: System name"
    },
    {
     "expr": "sum by (job,device_name,model) (\n  kentik_snmp_Uptime{job=~\"$job\",device_name=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Version"
    },
    {
     "expr": "(\n  sum by (job,device_name) (\n  kentik_snmp_Uptime{job=~\"$job\",device_name=~\"$instance\"}\n)\n)/100",
     "legendFormat": "{{instance}}: Uptime"
    },
    {
     "expr": "avg by (job,device_name) (\n  kentik_snmp_CPU{job=~\"$job\",device_name=~\"$instance\"}\n)",
     "legendFormat": "{{device_name}}: CPU utilization"
    },
    {
     "expr": "avg by (job,device_name) (\n  kentik_snmp_MemoryUtilization{job=~\"$job\",device_name=~\"$instance\"}\n)",
     "legendFormat": "{{device_name}}: Memory utilization"
    },
    {
     "expr": "\n  (\n  sum by (job,device_name) (\n  irate(kentik_snmp_ifHCOutOctets{job=~\"$job\",device_name=~\"$instance\"} [$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9",
     "legendFormat": "{{device_name}}: transmitted"
    },
    {
     "expr": "\n  (\n  sum by (job,device_name) (\n  irate(kentik_snmp_ifHCInOctets{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9",
     "legendFormat": "{{device_name}}: received"
    },
    {
     "expr": "sum by (job,device_name) (irate(kentik_snmp_ifOutErrors{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval])) +\nsum by (job,device_name) (irate(kentik_snmp_ifInErrors{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval])) +\nsum by (job,device_name) (irate(kentik_snmp_ifInDiscards{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval])) +\nsum by (job,device_name) (irate(kentik_snmp_ifOutDiscards{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{device_name}}: errors and drops"
    },
    {
     "expr": "count by (instance,job)(\n  count by (job,instance,alertname) (max_over_time(ALERTS{alertstate=\"firing\", severity=\"warning\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n  * on(job,instance) group_left group by (job,instance) (sysUpTime{job=~\"$job\",instance=~\"$instance\"})\n\n)",
     "legendFormat": "{{instance}}: Warnings"
    },
    {
     "expr": "count by (instance,job)(\n  count by (job,instance,alertname) (max_over_time(ALERTS{alertstate=\"firing\", severity=\"critical\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n  * on(job,instance) group_left group by (job,instance) (sysUpTime{job=~\"$job\",instance=~\"$instance\"})\n\n)",
     "legendFormat": "{{instance}}: Critical"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "Network interface traffic out.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  irate(kentik_snmp_ifHCOutOctets{job=~\"$job\",device_name=~\"$instance\"} [$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9\n)",
     "legendFormat": "{{device_name}}: transmitted"
    },
    {
     "expr": "topk(25,\n  \n  (\n  sum by (job,device_name) (\n  irate(kentik_snmp_ifHCInOctets{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9\n)",
     "legendFormat": "{{device_name}}: received"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "description": "Network interface errors in.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  kentik_snmp_ifInErrors{job=~\"$job\",device_name=~\"$instance\"}\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: errors in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  kentik_snmp_ifOutErrors{job=~\"$job\",device_name=~\"$instance\"}\n)\n)>0\n)",
     "legendFormat": "{{instance}}: errors out"
    }
   ]
  },
  {
   "title": "Packets dropped",
   "type": "timeseries",
   "description": "Network interface discards in.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  irate(kentik_snmp_ifInDiscards{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: dropped in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  irate(kentik_snmp_ifOutDiscards{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: dropped out"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  irate(ifInUnknownProtos{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: unknown dropped in"
    }
   ]
  },
  {
   "title": "Unicast",
   "type": "timeseries",
   "description": "Network interface unicast packets in.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  kentik_snmp_ifHCInUcastPkts{job=~\"$job\",device_name=~\"$instance\"}\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: unicast in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  kentik_snmp_ifHCOutUcastPkts{job=~\"$job\",device_name=~\"$instance\"}\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: unicast out"
    }
   ]
  },
  {
   "title": "Broadcast",
   "type": "timeseries",
   "description": "Network interface broadcast packets in.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  kentik_snmp_ifHCInBroadcastPkts{job=~\"$job\",device_name=~\"$instance\"}\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: broadcast in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  kentik_snmp_ifHCOutBroadcastPkts{job=~\"$job\",device_name=~\"$instance\"}\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: broadcast out"
    }
   ]
  },
  {
   "title": "Multicast",
   "type": "timeseries",
   "description": "Network interface multicast packets in.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  irate(kentik_snmp_ifHCInMulticastPkts{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: multicast in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,device_name) (\n  irate(kentik_snmp_ifHCOutMulticastPkts{job=~\"$job\",device_name=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{device_name}}: multicast out"
    }
   ]
  }
 ]
}