#!/usr/bin/env python3
"""Render k8s/generated/ from the same groups/*.env as Compose.

This is another *runtime* for the KtransToGrafana workflow, not a fork:
  groups/*.env → make generate → poller/discovery/catalog YAML
               → this script → Kubernetes manifests

Usage:
  python3 scripts/generate-k8s.py
  python3 scripts/generate-k8s.py --dry-run
  python3 scripts/generate-k8s.py --skip-generate   # reuse existing config/

See k8s/LIMITATIONS.md before you point network gear at a cluster.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "k8s" / "generated"
SCRIPTS = REPO / "k8s" / "scripts"


def load_dotenv(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.is_file():
        return env
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def parse_group_env(path: Path) -> dict[str, str]:
    data = load_dotenv(path)
    role = (data.get("ROLE") or "both").strip().lower() or "both"
    required = ["GROUP"]
    if role != "discover":
        required.extend(("METALISTEN_PORT", "TRAP_PORT"))
    missing = [k for k in required if not data.get(k)]
    if missing:
        raise SystemExit(f"{path.name}: missing {', '.join(missing)}")
    return data


def group_role(g: dict[str, str]) -> str:
    return (g.get("ROLE") or "both").strip().lower() or "both"


def is_poller(g: dict[str, str]) -> bool:
    return group_role(g) in {"poll", "both"}


def is_discoverer(g: dict[str, str]) -> bool:
    return group_role(g) in {"discover", "both"}


def run_generate_groups() -> None:
    script = REPO / "scripts" / "generate-groups.sh"
    subprocess.run(["bash", str(script)], cwd=REPO, check=True)


def ktrans_host(dotenv: dict[str, str]) -> str:
    explicit = dotenv.get("KTRANS_HOST", "").strip()
    if explicit:
        return explicit
    try:
        return subprocess.check_output(
            ["bash", str(REPO / "scripts" / "host-id.sh")],
            cwd=REPO,
            text=True,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return os.uname().nodename.split(".")[0]


def indent(text: str, n: int = 4) -> str:
    pad = " " * n
    return "\n".join(pad + line if line else "" for line in text.rstrip().splitlines())


def header() -> str:
    return (
        "# GENERATED by scripts/generate-k8s.py — do not edit by hand.\n"
        "# Re-run: make generate-k8s\n"
    )


def write_out(name: str, body: str, dry_run: bool) -> None:
    # kustomize rejects a comment-only first document; keep kustomization.yaml bare.
    prefix = "" if name == "kustomization.yaml" else header()
    content = prefix + body.lstrip() + ("\n" if not body.endswith("\n") else "")
    dest = OUT / name
    if dry_run:
        print(f"--- {dest.name} ({len(content)} bytes)")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {dest.relative_to(REPO)}")


def read_script(name: str) -> str:
    path = SCRIPTS / name
    if not path.is_file():
        raise SystemExit(f"missing {path}")
    return path.read_text(encoding="utf-8")


class Ctx:
    def __init__(self, dotenv: dict[str, str], groups: list[dict[str, str]]) -> None:
        self.env = dotenv
        self.groups = groups
        self.ns = dotenv.get("K8S_NAMESPACE", "ktrans") or "ktrans"
        self.mode = (dotenv.get("K8S_INGRESS_MODE") or "hostnetwork").strip().lower()
        if self.mode not in {"hostnetwork", "loadbalancer"}:
            raise SystemExit("K8S_INGRESS_MODE must be hostnetwork or loadbalancer")
        self.node = (dotenv.get("K8S_COLLECTOR_NODE") or "").strip()
        self.collector_ip = (dotenv.get("K8S_COLLECTOR_IP") or "").strip()
        self.lb_ip = (dotenv.get("K8S_LOADBALANCER_IP") or self.collector_ip).strip()
        self.preserve_src = (dotenv.get("K8S_PRESERVE_SOURCE_IP") or "1").strip() not in {
            "0",
            "false",
            "no",
        }
        self.alloy_mode = (dotenv.get("K8S_ALLOY_MODE") or "cluster").strip().lower()
        if self.alloy_mode not in {"cluster", "hostnetwork"}:
            raise SystemExit("K8S_ALLOY_MODE must be cluster or hostnetwork")
        self.storage_class = (dotenv.get("K8S_STORAGE_CLASS") or "").strip()
        self.storage_size = (dotenv.get("K8S_STORAGE_SIZE") or "1Gi").strip()
        self.discover_sched = (dotenv.get("K8S_DISCOVER_SCHEDULE") or "0 */6 * * *").strip()
        self.ktranslate = dotenv.get("KTRANSLATE_IMAGE") or "quay.io/kentik/ktranslate:latest"
        self.alloy = dotenv.get("ALLOY_IMAGE") or "grafana/alloy:latest"
        self.flow_dns = dotenv.get("FLOW_DNS_IMAGE") or "andyshinn/dnsmasq:2.83"
        self.yq = dotenv.get("K8S_YQ_IMAGE") or "mikefarah/yq:4"
        self.busybox = dotenv.get("K8S_BUSYBOX_IMAGE") or "busybox:1.36"
        self.nf_source = dotenv.get("NF_SOURCE") or "auto"
        self.syslog_source = dotenv.get("SYSLOG_SOURCE") or "0.0.0.0:1514"
        self.host = ktrans_host(dotenv)
        self.host_network = self.mode == "hostnetwork"
        if self.alloy_mode == "hostnetwork":
            self.otel = "http://127.0.0.1:4317/"
        else:
            self.otel = f"http://alloy.{self.ns}.svc.cluster.local:4317/"
        self.dns = f"flow-dns.{self.ns}.svc.cluster.local:53"

    def otel_name(self, base: str) -> str:
        return f"{base}-{self.host}" if self.host else base

    def node_selector(self, n: int = 6) -> str:
        if not self.node:
            return ""
        pad = " " * n
        return (
            f"{pad}nodeSelector:\n"
            f"{pad}  kubernetes.io/hostname: {self.node}\n"
        )

    def host_net_spec(self, n: int = 6) -> str:
        if not self.host_network:
            return self.node_selector(n)
        pad = " " * n
        return (
            f"{pad}hostNetwork: true\n"
            f"{pad}dnsPolicy: ClusterFirstWithHostNet\n"
            f"{self.node_selector(n)}"
        )

    def recreate(self) -> str:
        return "  strategy:\n    type: Recreate\n"

    def ktrans_env(self, service_base: str) -> str:
        return f"""          env:
            - name: OTEL_SERVICE_NAME
              value: {self.otel_name(service_base)}
            - name: OTEL_EXPORTER_OTLP_COMPRESSION
              value: gzip
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: ktrans-optional
                  key: AWS_REGION
                  optional: true
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ktrans-optional
                  key: AWS_ACCESS_KEY_ID
                  optional: true
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ktrans-optional
                  key: AWS_SECRET_ACCESS_KEY
                  optional: true
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ktrans-optional
                  key: AWS_SESSION_TOKEN
                  optional: true"""


def ns_yaml(c: Ctx) -> str:
    return f"""apiVersion: v1
kind: Namespace
metadata:
  name: {c.ns}
  labels:
    app.kubernetes.io/part-of: ktranstografana
"""


def identity_yaml(c: Ctx) -> str:
    ports = [
        "netflow=9995/udp",
        "syslog=1514/udp+tcp",
    ]
    for g in c.groups:
        if not is_poller(g):
            continue
        ports.append(f"traps_{g['GROUP']}={g['TRAP_PORT']}/udp")
    dest = c.collector_ip or (
        f"<node IP of {c.node}>" if c.node else "<SET K8S_COLLECTOR_IP>"
    )
    if c.mode == "loadbalancer":
        dest = c.lb_ip or "<pending LoadBalancer IP — reserve one>"
    warn = []
    if not c.collector_ip and c.mode == "hostnetwork":
        warn.append("K8S_COLLECTOR_IP is empty — stamp the pinned node's address on gear.")
    if c.mode == "hostnetwork" and not c.node:
        warn.append("K8S_COLLECTOR_NODE is empty — the collector IP can move on reschedule.")
    if c.mode == "loadbalancer" and not c.lb_ip:
        warn.append("K8S_LOADBALANCER_IP is empty — cloud will assign an ephemeral VIP.")
    if c.host_network and not c.node:
        warn.append("hostNetwork without a node pin is how destination IPs go ephemeral.")
    warning = " | ".join(warn) if warn else "collector identity looks pinned"
    port_block = "\n".join(f"    {p}" for p in ports)
    return f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: ktrans-collector-identity
  namespace: {c.ns}
  labels:
    app.kubernetes.io/part-of: ktranstografana
data:
  ingress_mode: {c.mode}
  alloy_mode: {c.alloy_mode}
  deployment_host: {c.host}
  collector_ip: {dest}
  collector_node: {c.node or "<unpinned>"}
  preserve_source_ip: {"true" if c.preserve_src else "false"}
  warning: {warning}
  stamp_on_gear: |
    Point traps / NetFlow / sFlow / syslog at {dest} (an IP, not a DNS name).
    Ports:
{port_block}
"""


def pvc_yaml(c: Ctx) -> str:
    sc = ""
    if c.storage_class:
        sc = f"  storageClassName: {c.storage_class}\n"
    return f"""apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ktrans-state
  namespace: {c.ns}
spec:
  accessModes:
    - ReadWriteOnce
{sc}  resources:
    requests:
      storage: {c.storage_size}
"""


def scripts_cm(c: Ctx) -> str:
    files = {
        "state-watch.sh": read_script("state-watch.sh"),
        "publish-devices.sh": read_script("publish-devices.sh"),
        "seed-state.sh": read_script("seed-state.sh"),
    }
    data = ""
    for name, body in files.items():
        data += f"  {name}: |\n{indent(body, 4)}\n"
    return f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: ktrans-scripts
  namespace: {c.ns}
data:
{data.rstrip()}
"""


def catalog_cm(c: Ctx) -> str:
    catalog = REPO / "config" / "catalog.yaml"
    if not catalog.is_file():
        raise SystemExit("missing config/catalog.yaml — run make generate first")
    alloy_src = REPO / "config.alloy"
    if not alloy_src.is_file():
        alloy_src = REPO / "config.alloy.sample"
    extra = REPO / "dnsmasq" / "extra-hosts.conf"
    extra_body = extra.read_text(encoding="utf-8") if extra.is_file() else "# none\n"
    dnsmasq = """# In-cluster flow_dns. Listen on all interfaces (no eth0 bind).
user=root
port=53
conf-dir=/etc/dnsmasq.d/,*.conf
addn-hosts=/state/flow-dns.hosts
"""
    return f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: ktranslate-catalog
  namespace: {c.ns}
data:
  catalog.yaml: |
{indent(catalog.read_text(encoding="utf-8"), 4)}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: {c.ns}
data:
  config.alloy: |
{indent(alloy_src.read_text(encoding="utf-8"), 4)}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-dns-config
  namespace: {c.ns}
data:
  dnsmasq.conf: |
{indent(dnsmasq, 4)}
  extra-hosts.conf: |
{indent(extra_body, 4)}
"""


def poller_cms(c: Ctx) -> str:
    docs = []
    for g in c.groups:
        name = g["GROUP"]
        if is_poller(g):
            poller = REPO / "config" / f"poller-{name}.yaml"
            if not poller.is_file():
                raise SystemExit(f"missing config/poller-{name}.yaml")
            docs.append(
                f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: ktranslate-poller-{name}
  namespace: {c.ns}
data:
  poller.yaml: |
{indent(poller.read_text(encoding="utf-8"), 4)}
"""
            )
        if is_discoverer(g):
            disc = REPO / "config" / f"discovery-{name}.yaml"
            if not disc.is_file():
                raise SystemExit(f"missing config/discovery-{name}.yaml")
            docs.append(
                f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: ktranslate-discovery-{name}
  namespace: {c.ns}
data:
  discovery.yaml: |
{indent(disc.read_text(encoding="utf-8"), 4)}
"""
            )
    return "\n---\n".join(docs)


def watch_sidecar(c: Ctx, watch_file: str, mode: str) -> str:
    return f"""        - name: state-watch
          image: {c.busybox}
          command: ["/bin/sh", "/scripts/state-watch.sh", "{watch_file}", "{mode}"]
          volumeMounts:
            - name: state
              mountPath: /state
              readOnly: true
            - name: scripts
              mountPath: /scripts
              readOnly: true
"""


def volumes_common(c: Ctx, extra: str = "") -> str:
    return f"""      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: ktrans-state
        - name: scripts
          configMap:
            name: ktrans-scripts
            defaultMode: 0755
{extra}"""


def alloy_yaml(c: Ctx) -> str:
    hostnet = ""
    if c.alloy_mode == "hostnetwork":
        hostnet = (
            "      hostNetwork: true\n"
            "      dnsPolicy: ClusterFirstWithHostNet\n"
            f"{c.node_selector(6)}"
        )
    else:
        hostnet = c.node_selector(6) if c.host_network else ""
    svc = ""
    if c.alloy_mode != "hostnetwork":
        svc = f"""---
apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: {c.ns}
spec:
  selector:
    app: alloy
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: ui
      port: 12346
      targetPort: 12346
"""
    return f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  namespace: {c.ns}
  labels:
    app: alloy
spec:
  replicas: 1
{c.recreate()}  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
{hostnet}      containers:
        - name: alloy
          image: {c.alloy}
          args:
            - --server.http.listen-addr=0.0.0.0:12346
            - --storage.path=/var/lib/alloy/data
            - --stability.level=experimental
            - run
            - /config.alloy
          env:
            - name: GC_OTLP_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-otlp
                  key: url
            - name: GC_OTLP_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: grafana-otlp
                  key: account
            - name: GC_OTLP_KEY
              valueFrom:
                secretKeyRef:
                  name: grafana-otlp
                  key: key
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "1000"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.host={c.host}
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: ui
              containerPort: 12346
          volumeMounts:
            - name: config
              mountPath: /config.alloy
              subPath: config.alloy
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: alloy-config
{svc}"""


def flow_dns_yaml(c: Ctx) -> str:
    return f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-dns
  namespace: {c.ns}
spec:
  replicas: 1
{c.recreate()}  selector:
    matchLabels:
      app: flow-dns
  template:
    metadata:
      labels:
        app: flow-dns
    spec:
{c.node_selector(6)}      containers:
        - name: dnsmasq
          image: {c.flow_dns}
          args: ["-k", "-C", "/etc/dnsmasq.conf"]
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/dnsmasq.conf
              subPath: dnsmasq.conf
              readOnly: true
            - name: config
              mountPath: /etc/dnsmasq.d/extra-hosts.conf
              subPath: extra-hosts.conf
              readOnly: true
            - name: state
              mountPath: /state
              readOnly: true
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: flow-dns-config
        - name: state
          persistentVolumeClaim:
            claimName: ktrans-state
---
apiVersion: v1
kind: Service
metadata:
  name: flow-dns
  namespace: {c.ns}
spec:
  selector:
    app: flow-dns
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
"""


def flow_yaml(c: Ctx) -> str:
    extra = """        - name: catalog
          configMap:
            name: ktranslate-catalog
"""
    ports = """            - name: netflow
              containerPort: 9995
              protocol: UDP
            - name: meta
              containerPort: 9996
              protocol: TCP"""
    return f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktranslate-flow
  namespace: {c.ns}
  labels:
    app: ktranslate-flow
spec:
  replicas: 1
{c.recreate()}  selector:
    matchLabels:
      app: ktranslate-flow
  template:
    metadata:
      labels:
        app: ktranslate-flow
    spec:
      shareProcessNamespace: true
{c.host_net_spec(6)}      containers:
        - name: ktranslate
          image: {c.ktranslate}
{c.ktrans_env("ktranslate-flow")}
          args:
            - --format=otel
            - --format_metric=otel
            - --otel.protocol=grpc
            - --otel.endpoint={c.otel}
            - --snmp=/snmp.yaml
            - --flow_only=true
            - --nf.source={c.nf_source}
            - --nf.port=9995
            - --metalisten=0.0.0.0:9996
            - --dns={c.dns}
            - --sinks=otel
            - --metrics=jchf
            - --tee_logs=true
            - --service_name=flow
            - --max_flows_per_message=100
            - --rollup_interval=60
            - --rollup_top_k=100
            - --rollups=s_sum,bytes_by_flow,in_bytes+out_bytes,src_addr,dst_addr,l4_src_port,l4_dst_port,protocol,custom_str.application,device_name,custom_str.src_host,custom_str.dst_host,src_geo,dst_geo
            - --rollup_keep_undefined=true
          ports:
{ports}
          volumeMounts:
            - name: catalog
              mountPath: /snmp.yaml
              subPath: catalog.yaml
              readOnly: true
            - name: state
              mountPath: /state
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
{watch_sidecar(c, "/state/devices-changed.flag", "term")}{volumes_common(c, extra)}
"""


def syslog_yaml(c: Ctx) -> str:
    extra = """        - name: catalog
          configMap:
            name: ktranslate-catalog
"""
    return f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktranslate-syslog
  namespace: {c.ns}
  labels:
    app: ktranslate-syslog
spec:
  replicas: 1
{c.recreate()}  selector:
    matchLabels:
      app: ktranslate-syslog
  template:
    metadata:
      labels:
        app: ktranslate-syslog
    spec:
      shareProcessNamespace: true
{c.host_net_spec(6)}      containers:
        - name: ktranslate
          image: {c.ktranslate}
{c.ktrans_env("ktranslate-syslog")}
          args:
            - --format=otel
            - --format_metric=otel
            - --otel.protocol=grpc
            - --otel.endpoint={c.otel}
            - --snmp=/snmp.yaml
            - --flow_only=true
            - --syslog.source={c.syslog_source}
            - --metalisten=0.0.0.0:9998
            - --sinks=otel
            - --metrics=jchf
            - --tee_logs=true
            - --service_name=syslog
          ports:
            - name: syslog-udp
              containerPort: 1514
              protocol: UDP
            - name: syslog-tcp
              containerPort: 1514
              protocol: TCP
            - name: meta
              containerPort: 9998
              protocol: TCP
          securityContext:
            capabilities:
              add: ["NET_BIND_SERVICE"]
          volumeMounts:
            - name: catalog
              mountPath: /snmp.yaml
              subPath: catalog.yaml
              readOnly: true
            - name: state
              mountPath: /state
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
{watch_sidecar(c, "/state/devices-changed.flag", "term")}{volumes_common(c, extra)}
"""


def snmp_yaml(c: Ctx) -> str:
    docs = []
    for g in c.groups:
        if not is_poller(g):
            continue
        name = g["GROUP"]
        trap = g["TRAP_PORT"]
        meta = g["METALISTEN_PORT"]
        extra = f"""        - name: poller
          configMap:
            name: ktranslate-poller-{name}
"""
        docs.append(
            f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktranslate-snmp-{name}
  namespace: {c.ns}
  labels:
    app: ktranslate-snmp-{name}
spec:
  replicas: 1
{c.recreate()}  selector:
    matchLabels:
      app: ktranslate-snmp-{name}
  template:
    metadata:
      labels:
        app: ktranslate-snmp-{name}
    spec:
      shareProcessNamespace: true
{c.host_net_spec(6)}      containers:
        - name: ktranslate
          image: {c.ktranslate}
{c.ktrans_env(f"ktranslate-snmp-{name}")}
          args:
            - --format=otel
            - --format_metric=otel
            - --otel.protocol=grpc
            - --otel.endpoint={c.otel}
            - --snmp=/snmp.yaml
            - --metalisten=0.0.0.0:{meta}
            - --sinks=otel
            - --metrics=jchf
            - --tee_logs=true
            - --service_name=snmp-{name}
            - --max_flows_per_message=100
          ports:
            - name: traps
              containerPort: {trap}
              protocol: UDP
            - name: meta
              containerPort: {meta}
              protocol: TCP
          securityContext:
            capabilities:
              add: ["NET_RAW", "NET_BIND_SERVICE"]
          volumeMounts:
            - name: poller
              mountPath: /snmp.yaml
              subPath: poller.yaml
              readOnly: true
            - name: state
              mountPath: /state
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 4Gi
{watch_sidecar(c, f"/state/devices-{name}.yaml", "usr2")}{volumes_common(c, extra)}
"""
        )
    return "\n---\n".join(docs)


def discover_env(c: Ctx) -> str:
    return """                - name: NETBOX_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ktrans-optional
                      key: NETBOX_HOST
                      optional: true
                - name: NETBOX_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ktrans-optional
                      key: NETBOX_TOKEN
                      optional: true
                - name: AWS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: ktrans-optional
                      key: AWS_REGION
                      optional: true
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: ktrans-optional
                      key: AWS_ACCESS_KEY_ID
                      optional: true
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ktrans-optional
                      key: AWS_SECRET_ACCESS_KEY
                      optional: true
                - name: AWS_SESSION_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ktrans-optional
                      key: AWS_SESSION_TOKEN
                      optional: true
                - name: OTEL_METRIC_EXPORT_INTERVAL
                  value: "10000"
"""


def discovery_yaml(c: Ctx) -> str:
    docs = []
    discoverers = [g for g in c.groups if is_discoverer(g)]
    for i, g in enumerate(discoverers):
        name = g["GROUP"]
        # Stagger cron minutes so groups do not scan at the same instant.
        sched = c.discover_sched
        parts = sched.split()
        if len(parts) == 5 and parts[0].isdigit():
            minute = (int(parts[0]) + i * 5) % 60
            parts[0] = str(minute)
            sched = " ".join(parts)
        docs.append(
            f"""apiVersion: batch/v1
kind: CronJob
metadata:
  name: discover-{name}
  namespace: {c.ns}
  labels:
    app: discover-{name}
spec:
  schedule: "{sched}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          restartPolicy: Never
{c.node_selector(10)}          initContainers:
            - name: seed-runtime
              image: {c.busybox}
              command: ["/bin/sh", "-c", "cp /config/discovery.yaml /state/discovery-{name}.runtime.yaml"]
              volumeMounts:
                - name: discovery
                  mountPath: /config
                  readOnly: true
                - name: state
                  mountPath: /state
            - name: discover
              image: {c.ktranslate}
              env:
                - name: OTEL_SERVICE_NAME
                  value: {c.otel_name(f"ktranslate-discover-{name}")}
{discover_env(c)}              args:
                - --format=otel
                - --format_metric=otel
                - --otel.protocol=grpc
                - --otel.endpoint={c.otel}
                - --snmp=/state/discovery-{name}.runtime.yaml
                - -snmp_discovery=true
                - --sinks=otel
                - --metrics=jchf
                - --tee_logs=true
                - --service_name=discover-{name}
              volumeMounts:
                - name: state
                  mountPath: /state
          containers:
            - name: publish
              image: {c.yq}
              command: ["/bin/sh", "/scripts/publish-devices.sh", "{name}"]
              volumeMounts:
                - name: state
                  mountPath: /state
                - name: scripts
                  mountPath: /scripts
                  readOnly: true
          volumes:
            - name: state
              persistentVolumeClaim:
                claimName: ktrans-state
            - name: discovery
              configMap:
                name: ktranslate-discovery-{name}
            - name: scripts
              configMap:
                name: ktrans-scripts
                defaultMode: 0755
"""
        )
    return "\n---\n".join(docs)


def bootstrap_yaml(c: Ctx) -> str:
    args = ", ".join(f'"{g["GROUP"]}"' for g in c.groups)
    return f"""apiVersion: batch/v1
kind: Job
metadata:
  name: ktrans-state-bootstrap
  namespace: {c.ns}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
{c.node_selector(6)}      containers:
        - name: seed
          image: {c.busybox}
          command: ["/bin/sh", "/scripts/seed-state.sh", {args}]
          volumeMounts:
            - name: state
              mountPath: /state
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: ktrans-state
        - name: scripts
          configMap:
            name: ktrans-scripts
            defaultMode: 0755
"""


def inbound_svc_yaml(c: Ctx) -> str:
    """Stable VIP for gear that cannot follow DNS. LoadBalancer mode only."""
    if c.mode != "loadbalancer":
        return ""
    policy = "Local" if c.preserve_src else "Cluster"
    lb = ""
    if c.lb_ip:
        lb = f"  loadBalancerIP: {c.lb_ip}\n"
    ports = [
        "    - name: netflow\n      port: 9995\n      protocol: UDP\n      targetPort: 9995",
        "    - name: syslog-udp\n      port: 1514\n      protocol: UDP\n      targetPort: 1514",
        "    - name: syslog-tcp\n      port: 1514\n      protocol: TCP\n      targetPort: 1514",
    ]
    seen = {"9995", "1514"}
    for g in c.groups:
        if not is_poller(g):
            continue
        trap = g["TRAP_PORT"]
        if trap in seen:
            continue
        seen.add(trap)
        ports.append(
            f"    - name: traps-{g['GROUP']}\n      port: {trap}\n      protocol: UDP\n      targetPort: {trap}"
        )
    # One Service cannot select multiple Deployments. Use a shared label.
    # Collectors in LB mode get app.kubernetes.io/inbound: "true" — added below
    # by patching would be messy; instead expose each listener as its own Service
    # sharing the same loadBalancerIP (MetalLB) or document per-Service IPs.
    #
    # Cloud LBs often want one IP per Service. We emit *one* Service per
    # listener so operators can attach the same reserved IP annotation/vendor
    # config, and we also emit a cheat-sheet ConfigMap.
    docs = []
    selectors = [
        ("ktranslate-inbound-flow", "ktranslate-flow", ports[0]),
        ("ktranslate-inbound-syslog", "ktranslate-syslog", "\n".join(ports[1:3])),
    ]
    for g in c.groups:
        if not is_poller(g):
            continue
        trap = g["TRAP_PORT"]
        selectors.append(
            (
                f"ktranslate-inbound-traps-{g['GROUP']}",
                f"ktranslate-snmp-{g['GROUP']}",
                f"    - name: traps\n      port: {trap}\n      protocol: UDP\n      targetPort: {trap}",
            )
        )
    for svc_name, app, port_block in selectors:
        docs.append(
            f"""apiVersion: v1
kind: Service
metadata:
  name: {svc_name}
  namespace: {c.ns}
  annotations:
    ktranstografana/collector-ip: "{c.lb_ip or "SET-K8S-LOADBALANCER-IP"}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: {policy}
{lb}  selector:
    app: {app}
  ports:
{port_block}
"""
        )
    return "\n---\n".join(docs)


def pdb_yaml(c: Ctx) -> str:
    """Honest PDB: one replica, so a drain *will* drop UDP briefly."""
    names = ["alloy", "ktranslate-flow", "ktranslate-syslog", "flow-dns"]
    names += [f"ktranslate-snmp-{g['GROUP']}" for g in c.groups if is_poller(g)]
    docs = []
    for name in names:
        docs.append(
            f"""apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {name}
  namespace: {c.ns}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {name}
"""
        )
    return "\n---\n".join(docs)


def endpoints_md(c: Ctx) -> str:
    dest = c.collector_ip or c.lb_ip or (
        f"IP of node {c.node}" if c.node else "<SET K8S_COLLECTOR_IP>"
    )
    rows = [
        "| Signal | Stamp on the device | Notes |",
        "|--------|---------------------|-------|",
        f"| NetFlow / IPFIX / sFlow (`NF_SOURCE={c.nf_source}`) | `{dest}:9995` UDP | One listener. Do not replica this Deployment. |",
        f"| Syslog | `{dest}:1514` UDP/TCP | Privileged port — needs NET_BIND_SERVICE. |",
    ]
    for g in c.groups:
        if not is_poller(g):
            continue
        rows.append(
            f"| SNMP traps (`{g['GROUP']}`) | `{dest}:{g['TRAP_PORT']}` UDP | Poller is also the trap sink. |"
        )
    warns = []
    if c.mode == "hostnetwork" and not c.node:
        warns.append("- **Unpinned hostNetwork:** the destination IP changes if the pod moves.")
    if c.mode == "loadbalancer" and not c.lb_ip:
        warns.append("- **No reserved VIP:** the cloud LB address can change on recreate.")
    if not c.preserve_src and c.mode == "loadbalancer":
        warns.append("- **externalTrafficPolicy=Cluster:** source IPs are SNATed; flow/trap identity suffers.")
    warn_block = "\n".join(warns) if warns else "- Collector identity looks pinned (still verify the IP on the node/LB)."
    return f"""# Collector endpoints — stamp these IPs on network gear

Kubernetes DNS names are for **in-cluster** traffic (ktranslate → Alloy).
Devices typically **cannot** follow DNS. Use the IP below.

**Mode:** `{c.mode}` · **Node:** `{c.node or "unpinned"}` · **deployment.host:** `{c.host}`

{chr(10).join(rows)}

## Warnings

{warn_block}

Read [k8s/LIMITATIONS.md](../LIMITATIONS.md) before you scale replicas or
add a second collector "for HA".
"""


def kustomization(names: list[str]) -> str:
    res = "\n".join(f"  - {n}" for n in names)
    return f"""apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
{res}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--skip-generate", action="store_true")
    args = ap.parse_args()

    dotenv = load_dotenv(REPO / ".env")
    dotenv.update({k: v for k, v in os.environ.items() if k.startswith("K8S_") or k in {
        "KTRANS_HOST", "KTRANSLATE_IMAGE", "ALLOY_IMAGE", "FLOW_DNS_IMAGE",
        "NF_SOURCE", "SYSLOG_SOURCE",
    }})

    group_files = sorted((REPO / "groups").glob("*.env"))
    if not group_files:
        raise SystemExit("no groups/*.env — copy a groups/*.env.sample first")
    groups = [parse_group_env(p) for p in group_files]

    if not args.skip_generate:
        try:
            run_generate_groups()
        except (subprocess.CalledProcessError, FileNotFoundError) as exc:
            print(f"WARN: generate-groups.sh failed ({exc}); using existing config/", file=sys.stderr)
            if not (REPO / "config" / "catalog.yaml").is_file():
                raise SystemExit("config/catalog.yaml missing and generate-groups.sh failed") from exc

    c = Ctx(dotenv, groups)
    if c.mode == "hostnetwork" and not c.node:
        print(
            "WARN: K8S_COLLECTOR_NODE is empty. hostNetwork pods can land on any "
            "node and the destination IP your gear has configured will go stale.",
            file=sys.stderr,
        )
    if c.mode == "loadbalancer" and not c.lb_ip:
        print(
            "WARN: K8S_LOADBALANCER_IP / K8S_COLLECTOR_IP is empty. "
            "The assigned VIP may be ephemeral.",
            file=sys.stderr,
        )

    files: list[tuple[str, str]] = [
        ("00-namespace.yaml", ns_yaml(c)),
        ("01-identity.yaml", identity_yaml(c)),
        ("02-pvc.yaml", pvc_yaml(c)),
        ("03-scripts.yaml", scripts_cm(c)),
        ("04-catalog.yaml", catalog_cm(c)),
        ("10-alloy.yaml", alloy_yaml(c)),
        ("20-flow-dns.yaml", flow_dns_yaml(c)),
        ("30-flow.yaml", flow_yaml(c)),
        ("40-syslog.yaml", syslog_yaml(c)),
        ("61-bootstrap.yaml", bootstrap_yaml(c)),
        ("80-pdb.yaml", pdb_yaml(c)),
    ]
    pollers = poller_cms(c)
    if pollers:
        files.append(("05-pollers.yaml", pollers))
    snmp = snmp_yaml(c)
    if snmp:
        files.append(("50-snmp.yaml", snmp))
    disco = discovery_yaml(c)
    if disco:
        files.append(("60-discovery.yaml", disco))
    files.sort(key=lambda t: t[0])
    inbound = inbound_svc_yaml(c)
    if inbound:
        files.append(("70-inbound-svc.yaml", inbound))

    names = [n for n, _ in files]
    files.append(("kustomization.yaml", kustomization(names)))

    if not args.dry_run:
        if OUT.exists():
            for old in OUT.glob("*.yaml"):
                old.unlink()
            ep = OUT / "COLLECTOR-ENDPOINTS.md"
            if ep.exists():
                ep.unlink()

    for name, body in files:
        write_out(name, body, args.dry_run)
    write_out("COLLECTOR-ENDPOINTS.md", endpoints_md(c), args.dry_run)

    print()
    print(f"namespace={c.ns} mode={c.mode} host={c.host} groups={len(c.groups)}")
    print("apply:  bash scripts/deploy-k8s.sh")
    print("read:   k8s/LIMITATIONS.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
