#!/usr/bin/env bash
# Generate per-group ktranslate configs and a Compose service fragment from
# the declarative files in groups/*.env. Run this:
#   - once during initial setup
#   - whenever you add, remove, or modify a group
# Then bring the stack up:
#   docker compose -f compose-base.yaml -f compose-groups.generated.yaml up -d
#
# Requires: bash, envsubst (apt install gettext-base on Ubuntu).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GROUPS_DIR="${REPO_ROOT}/groups"
TEMPLATES_DIR="${REPO_ROOT}/templates"
CONFIG_DIR="${REPO_ROOT}/config"
STATE_DIR="${REPO_ROOT}/state"
COMPOSE_OUT="${REPO_ROOT}/compose-groups.generated.yaml"
# REPO_PATH ends up baked into the bind-mount sources of the rendered
# compose-groups.generated.yaml. Default to REPO_ROOT (where the script
# lives), but let the caller override — needed when this script runs from
# inside a container (e.g. the ktranslate-tools admin sidecar) that has a
# different idea of its own filesystem layout than the docker host does.
REPO_PATH="${REPO_PATH:-${REPO_ROOT}}"
export REPO_PATH

if ! command -v envsubst >/dev/null 2>&1; then
  echo "ERROR: envsubst not found. Install with: sudo apt install gettext-base" >&2
  exit 1
fi

mkdir -p "${CONFIG_DIR}" "${STATE_DIR}"

# Only the placeholders listed here get substituted. Everything else
# (notably docker compose's own ${OTEL_SERVICE_NAME}, ${NF_SOURCE}, ${GC_*})
# stays literal so docker compose can resolve it from .env at runtime.
SUBST_VARS='$GROUP $METALISTEN_PORT $TRAP_PORT $TRAP_COMMUNITY $DISCOVERY_THREADS $POLL_INTERVAL_SEC $TARGETS_YAML $DEFAULT_COMMUNITIES_YAML $DEFAULT_V3_YAML $REPO_PATH'

shopt -s nullglob
GROUP_FILES=("${GROUPS_DIR}"/*.env)
shopt -u nullglob
if [[ ${#GROUP_FILES[@]} -eq 0 ]]; then
  echo "ERROR: no group files found in ${GROUPS_DIR}/*.env" >&2
  echo "       Copy groups/<name>.env.sample to groups/<name>.env to define a group." >&2
  exit 1
fi

# ---------- Pre-pass: validate every group file and detect collisions ----------
declare -A USED_ML_PORTS
declare -A USED_TRAP_PORTS
# Ports used by the static services in compose-base.yaml. Any group claiming
# one of these would fail at `docker compose up` time; catch it here instead.
RESERVED_PORTS_TCP="9995 9996 9998 4317 12346"
RESERVED_PORTS_UDP="1514"

for env_file in "${GROUP_FILES[@]}"; do
  (
    set -a
    # shellcheck disable=SC1090
    source "${env_file}"
    set +a

    for var in GROUP SNMP_VERSION TRAP_COMMUNITY TARGETS METALISTEN_PORT TRAP_PORT DISCOVERY_THREADS POLL_INTERVAL_SEC; do
      if [[ -z "${!var:-}" ]]; then
        echo "ERROR: ${env_file}: missing required variable ${var}" >&2
        exit 1
      fi
    done

    case "${SNMP_VERSION}" in
      v2c)
        if [[ -z "${SNMP_V2_COMMUNITY:-}" ]]; then
          echo "ERROR: ${env_file}: SNMP_VERSION=v2c requires SNMP_V2_COMMUNITY" >&2
          exit 1
        fi ;;
      v3)
        for var in SNMP_V3_USER SNMP_V3_AUTH_PROTOCOL SNMP_V3_AUTH_PASS SNMP_V3_PRIV_PROTOCOL SNMP_V3_PRIV_PASS; do
          if [[ -z "${!var:-}" ]]; then
            echo "ERROR: ${env_file}: SNMP_VERSION=v3 requires ${var}" >&2
            exit 1
          fi
        done ;;
      *) echo "ERROR: ${env_file}: SNMP_VERSION must be v2c or v3, got '${SNMP_VERSION}'" >&2; exit 1 ;;
    esac
  )

  GN=$(awk -F= '/^GROUP=/{print $2; exit}'           "${env_file}")
  ML=$(awk -F= '/^METALISTEN_PORT=/{print $2; exit}' "${env_file}")
  TR=$(awk -F= '/^TRAP_PORT=/{print $2; exit}'       "${env_file}")
  if [[ -n "${USED_ML_PORTS[${ML}]:-}" ]]; then
    echo "ERROR: METALISTEN_PORT ${ML} used by both '${USED_ML_PORTS[${ML}]}' and '${GN}'" >&2
    exit 1
  fi
  if [[ -n "${USED_TRAP_PORTS[${TR}]:-}" ]]; then
    echo "ERROR: TRAP_PORT ${TR} used by both '${USED_TRAP_PORTS[${TR}]}' and '${GN}'" >&2
    exit 1
  fi
  for r in ${RESERVED_PORTS_TCP}; do
    if [[ "${ML}" == "${r}" ]]; then
      echo "ERROR: METALISTEN_PORT ${ML} (group ${GN}) collides with a static service" >&2
      exit 1
    fi
  done
  for r in ${RESERVED_PORTS_UDP}; do
    if [[ "${TR}" == "${r}" ]]; then
      echo "ERROR: TRAP_PORT ${TR} (group ${GN}) collides with a static service" >&2
      exit 1
    fi
  done
  USED_ML_PORTS[${ML}]="${GN}"
  USED_TRAP_PORTS[${TR}]="${GN}"
done

# ---------- Render pass ----------
cat > "${COMPOSE_OUT}" <<EOF
# GENERATED by scripts/generate-groups.sh from groups/*.env — do not edit by hand.
# Merge with compose-base.yaml at runtime:
#   docker compose -f compose-base.yaml -f compose-groups.generated.yaml up -d
services:
EOF

for env_file in "${GROUP_FILES[@]}"; do
  (
    set -a
    # shellcheck disable=SC1090
    source "${env_file}"
    set +a

    # Indented YAML list of scan targets.
    TARGETS_YAML=""
    IFS=',' read -ra TGT_ARR <<< "${TARGETS}"
    for t in "${TGT_ARR[@]}"; do
      t="${t// /}"
      TARGETS_YAML+="      - ${t}"$'\n'
    done
    TARGETS_YAML="${TARGETS_YAML%$'\n'}"
    export TARGETS_YAML

    # Render the credential blocks conditional on SNMP version. The exact
    # leading whitespace matters — these slot into `default_communities:`
    # and `default_v3:` placeholders that are themselves at 4-space indent.
    if [[ "${SNMP_VERSION}" == "v2c" ]]; then
      DEFAULT_COMMUNITIES_YAML=$'\n      - '"${SNMP_V2_COMMUNITY}"
      DEFAULT_V3_YAML=" null"
    else
      DEFAULT_COMMUNITIES_YAML=" []"
      DEFAULT_V3_YAML=$(cat <<EOF

        user_name: ${SNMP_V3_USER}
        authentication_protocol: ${SNMP_V3_AUTH_PROTOCOL}
        authentication_passphrase: ${SNMP_V3_AUTH_PASS}
        privacy_protocol: ${SNMP_V3_PRIV_PROTOCOL}
        privacy_passphrase: ${SNMP_V3_PRIV_PASS}
        context_engine_id: ""
        context_name: ""
EOF
)
    fi
    export DEFAULT_COMMUNITIES_YAML DEFAULT_V3_YAML

    envsubst "${SUBST_VARS}" < "${TEMPLATES_DIR}/discovery.yaml.tmpl" \
      > "${CONFIG_DIR}/discovery-${GROUP}.yaml"
    envsubst "${SUBST_VARS}" < "${TEMPLATES_DIR}/poller.yaml.tmpl" \
      > "${CONFIG_DIR}/poller-${GROUP}.yaml"
    envsubst "${SUBST_VARS}" < "${TEMPLATES_DIR}/compose-snippet.yaml.tmpl" \
      >> "${COMPOSE_OUT}"

    echo "  rendered ${GROUP}  (snmp=${SNMP_VERSION}  ports=${METALISTEN_PORT}/${TRAP_PORT})"
  )
done

echo
echo "wrote $(ls "${CONFIG_DIR}"/discovery-*.yaml 2>/dev/null | wc -l) discovery configs, $(ls "${CONFIG_DIR}"/poller-*.yaml 2>/dev/null | wc -l) poller configs, and ${COMPOSE_OUT}"
